version: "3.7"

services:
  web:
    build: ./docker/nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ssl_info:/etc/nginx/ssl
      - .:/app
      - auth_source:/simplesamlphp/www
      # - ./var/log:/log
    depends_on:
      - app
      - idp

  idp:
    build: ./docker/simplesamlphp
    ports:
        - 9001:9001
    volumes:
        - auth_source:/simplesamlphp/www
        - ssl_info:/simplesamlphp/cert

  app:
    build: .
    ports:
      - 9000:9000
    volumes:
      - .:/app
      # - ./var:/app/var

  db:
    image: mysql:8.0.17
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: "true"
        MYSQL_DATABASE: my_database
        MYSQL_USER: my_user
        MYSQL_PASSWORD: my_password
    ports:
        - 3306:3306
        - 33060:33060
    volumes:
        - db_data:/var/lib/mysql

volumes:
  ssl_info:
  auth_source:
  db_data:
